In [1]:
%load_ext autoreload
%autoreload 2
%aimport numpy
import numpy as np
from cryptic_solver import (
    StandardSolver,
    CrypticSolver,
    SandwichSolver,
    ThermometerSolver,
)

In [2]:
%%time
ss = StandardSolver(
    np.array(
        [
            [7, 5, 2, 0, 0, 1, 4, 0, 0],
            [0, 3, 0, 0, 0, 6, 0, 0, 1],
            [6, 4, 0, 0, 7, 0, 3, 2, 0],
            [8, 0, 5, 2, 6, 0, 0, 0, 0],
            [0, 0, 0, 3, 0, 4, 0, 0, 0],
            [0, 0, 0, 0, 8, 5, 2, 0, 6],
            [0, 8, 9, 0, 5, 0, 0, 1, 4],
            [4, 0, 0, 9, 0, 0, 0, 7, 0],
            [0, 0, 7, 6, 0, 0, 9, 3, 2],
        ]
    )
)
ss.solve()

[[7 5 2 8 3 1 4 6 9]
 [9 3 8 4 2 6 7 5 1]
 [6 4 1 5 7 9 3 2 8]
 [8 9 5 2 6 7 1 4 3]
 [1 2 6 3 9 4 5 8 7]
 [3 7 4 1 8 5 2 9 6]
 [2 8 9 7 5 3 6 1 4]
 [4 6 3 9 1 2 8 7 5]
 [5 1 7 6 4 8 9 3 2]]
Wall time: 267 ms


In [3]:
%%time
cs = CrypticSolver(
    np.array(
        [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 2, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ]
    )
)
cs.solve()

[[4 8 3 7 2 6 1 5 9]
 [7 2 6 1 5 9 4 8 3]
 [1 5 9 4 8 3 7 2 6]
 [8 3 7 2 6 1 5 9 4]
 [2 6 1 5 9 4 8 3 7]
 [5 9 4 8 3 7 2 6 1]
 [3 7 2 6 1 5 9 4 8]
 [6 1 5 9 4 8 3 7 2]
 [9 4 8 3 7 2 6 1 5]]
Wall time: 1.29 s


In [4]:
%%time
sws = SandwichSolver(
    np.array(
        [
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 9, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 6, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 1, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 2, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 7, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
        ]
    ),
    row_sums=np.array([2, 8, 26, 29, 0, 23, 15, 2, 4]),
    col_sums=np.array([10, 23, 23, 23, 14, 12, 21, 0, 0]),
)
sws.solve()

[[6 1 2 9 3 8 4 7 5]
 [7 8 3 4 5 1 2 6 9]
 [4 5 9 2 6 7 8 3 1]
 [1 3 8 6 7 5 9 4 2]
 [2 7 4 3 1 9 5 8 6]
 [5 9 6 8 4 2 3 1 7]
 [3 4 5 1 2 6 7 9 8]
 [9 2 1 7 8 3 6 5 4]
 [8 6 7 5 9 4 1 2 3]]
Wall time: 1min 13s


In [5]:
%%time
ts = ThermometerSolver(
    np.array(
        [
            [0, 0, 0, 0, 0, 0, 5, 0, 4],
            [0, 0, 0, 0, 0, 0, 0, 6, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 2, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 0, 1, 0, 0, 0, 0, 0, 0],
            [0, 0, 0, 0, 0, 0, 0, 0, 0],
            [0, 9, 0, 0, 0, 0, 0, 3, 0],
            [7, 0, 8, 0, 0, 0, 0, 0, 0],
        ]
    ),
    paths=[
        [(0, 0), (0, 1), (1, 1), (2, 1), (3, 1)],
        [(2, 3), (2, 4), (2, 5), (3, 5), (4, 5), (4, 4)],
        [(4, 0), (4, 1), (4, 2)],
        [(4, 3), (5, 3), (6, 3), (6, 4), (6, 5)],
        [(8, 6), (8, 7), (8, 8), (7, 8), (6, 8), (6, 7), (6, 6)],
        [(4, 6), (4, 7), (4, 8), (5, 8)],
    ],
)
ts.solve()

[[1 2 3 8 6 9 5 7 4]
 [8 4 9 5 7 1 3 6 2]
 [6 5 7 2 3 4 8 9 1]
 [9 8 4 6 2 5 7 1 3]
 [2 3 6 1 9 7 4 5 8]
 [5 7 1 3 4 8 6 2 9]
 [3 1 2 4 5 6 9 8 7]
 [4 9 5 7 8 2 1 3 6]
 [7 6 8 9 1 3 2 4 5]]
Wall time: 46.9 s
